authorName: Iman Mirzadeh
experimentName: LCM_CIFAR-Explore-LCM
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 1500

#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: cifar_search.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: Random
trial:
  command: python train.py
  codeDir: ..
  gpuNum: 1