authorName: Iman Mirzadeh
experimentName: LCM_ROT-Explore-LCM
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 1500

#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: lcm_20_offline_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: Random
trial:
  command: python experiment_2.py
  codeDir: ..
  gpuNum: 1